[Breaking] Operationalise up- and download
CommonGateway/ZGWBundle pull request #33
Opened 2023-04-04 11:59 UTC by rjzondervan

Operationalises up- and downloads of documents into a different entity, and show a link in the original object.

Please note: this breaks compatibility with previous versions.

2023-04-04 13:49 UTC, bbrands02 approved these changes

2023-04-04 13:49 UTC, bbrands02 commented on Service/ZGWService.php
> +    private function generateDownloadEndpoint(string $id, Endpoint $downloadEndpoint): string
Docblocks?

2023-04-04 14:00 UTC, WilcoLouwerse requested changes
Mostly style stuff

2023-04-04 14:00 UTC, WilcoLouwerse commented on ActionHandler/InhoudHandler.php
> +            '$schema'     => 'https://json-schema.org/draft/2020-12/schema',
'$id'             => 'https://vng.opencatalogi.nl/ActionHandler/drc.InhoudHandler.ActionHandler.json',
'$schema'    => 'https://docs.commongateway.nl/schemas/ActionHandler.schema.json',
Voor consistency

2023-04-04 14:00 UTC, WilcoLouwerse commented on Service/ZGWService.php
> +
lot of empty lines^
I think this function also needs a return statement here?

2023-04-05 08:26 UTC, bbrands02 approved these changes

2023-04-05 08:40 UTC, smisidjan approved these changes

2023-04-05 08:45 UTC, merged